### ISSUE TITLE
Where can i find the regression tests?

### ISSUE THREAD

**Issue by Azq2** [FreeRTOS/Lab-Project-FreeRTOS-FAT#13]
I see this line in ff_dir.c
```
#warning This path is not yet included in the regression tests.
```

But i don't find any regression tests in this repository. 

Where can I find regression tests to improve them?

**Comment by n9wxu** [comment]
Historically, demos in FreeRTOS are programs used to test the functionality.  So the FAT demos here: https://github.com/FreeRTOS/FreeRTOS-Labs/tree/master/FreeRTOS-Labs/Demo/Common/FreeRTOS_Plus_FAT_Demos
are the tests used to verify operations.

Additionally a manual stress test of FTPing thousands of files to a RAM disk and then FTPing them back for verification for a  first order function check.

We welcome any assistance in creating a robust set of tests for the FAT file system.

**Comment by htibosch** [comment]
Thanks @n9wxu for showing where these tests can be found.

The test will run a couple of tasks at idle priority, while the following macros are set:
~~~c
#define configUSE_PREEMPTION       1
#define configUSE_TIME_SLICING     1
#define configIDLE_SHOULD_YIELD    1
~~~

This will also test if the access to the disk is protected / synchronised in a proper.way.

And indeed, the +FAT driver was also tested heavily by copying tons of small and large files to an SD-card and back to a host.
The contents of all files were compared to the originals copies.
After the test, the SD-card was mounted into a Linux machine to check the integrity of the file system.

And yes, please contribute ! Thanks.
