### ISSUE TITLE
ff_fseek function seems to be malfunctioning 

### ISSUE THREAD

**Issue by MateuszKlatecki** [FreeRTOS/Lab-Project-FreeRTOS-FAT#15]
The ff_fseek function seems to be malfunctioning and the file writes are not correct.

Below is an example code that causes problems. It is important that the clusterSize variable is set to the correct cluster size.

```c
    // set a valid cluster size
    const int clusterSize = 4096;

    char *buffer = malloc(clusterSize);

    memset(buffer, 'A', clusterSize);
    FF_FILE *file = ff_fopen("testFile.txt", "w");
    ff_fseek(file, 0, FF_SEEK_SET);
    ff_fwrite(buffer, 1, clusterSize, file);
    ff_fclose(file);

    memset(buffer, 'B', clusterSize);
    file = ff_fopen("testFile.txt", "r+");
    ff_fseek(file, clusterSize, FF_SEEK_SET);
    ff_fwrite(buffer, 1, clusterSize, file);
    ff_fclose(file);
```

Execution of the above code should create a file with a size of 8192 bytes and a content of 4096 letters A and 4096 B, but its content is completely different.

Below is the configuration I am using:

```c
#define ffconfigBYTE_ORDER                pdFREERTOS_LITTLE_ENDIAN
#define ffconfigHAS_CWD                   1
#define ffconfigLFN_SUPPORT               1
#define ffconfigSHORTNAME_CASE            1
#define ffconfigOPTIMISE_UNALIGNED_ACCESS 0
#define ffconfigCACHE_WRITE_THROUGH       1
#define ffconfigWRITE_BOTH_FATS           1
#define ffconfigTIME_SUPPORT              1
#define ffconfigPATH_CACHE                1
#define ffconfigPATH_CACHE_DEPTH          5
#define ffconfigHASH_CACHE                1
#define ffconfigHASH_CACHE_DEPTH          16
#define ffconfig64_NUM_SUPPORT            1
#define ffconfigCWD_THREAD_LOCAL_INDEX    0
#define ffconfigFAT_CHECK                 1
#define ffconfigUSE_DELTREE               1
```

**Comment by sukhmanm** [comment]
Hi @MateuszKlatecki,

Thank you for raising this issue. Do you receive [an error](https://www.freertos.org/FreeRTOS-Plus/FreeRTOS_Plus_FAT/stdio_API/ff_errno.html) from the second call to `ff_fseek()`? The utility functions [ff_filelength()](https://www.freertos.org/FreeRTOS-Plus/FreeRTOS_Plus_FAT/stdio_API/ff_filelength.html) and [`ff_feof()`](https://www.freertos.org/FreeRTOS-Plus/FreeRTOS_Plus_FAT/stdio_API/ff_feof.html) may also be helpful in determining if the stream pointer is being moved correctly. Alternatively, you could try opening the file with "a+", which would allow you to append data to the end of the existing file instead of using `ff_fseek()`. 

Let me know if you are able to verify the error codes to further pinpoint the issue. Thanks.

**Comment by MateuszKlatecki** [comment]
I don't have access to the hardware right now to be able to 100% confirm it (I will be able to do it after the weekend) but as far as I remember, the second ff_fseek call did not return an error. After the second write, the file size was also correct, but its contents were incorrect - the second part of the file contained garbage. 

It looked as if the cluster map was damaged - the last part of the chain pointed to the wrong cluster (or the second write was to the wrong cluster)

I also checked for several different cluster sizes and the result was the same - file is corrupted.

**Comment by htibosch** [comment]
@MateuszKlatecki, can you tell me which platform you are using? What hardware driver are you using?

Your sample code looks good to me, and you are right that `AAA...BBB...` is to be expected.

You open the file in update more "r+", which is also good. The format characters are interpreted [here](https://github.com/FreeRTOS/Lab-Project-FreeRTOS-FAT/blob/97e608cca689c702fb51e386d4df9e9ea0ee88a6/ff_file.c#L64).

I will run your code on some boards and see what the results are.

**Comment by htibosch** [comment]
I copied [Mateusz'](https://github.com/MateuszKlatecki) settings to my `FreeRTOSFATConfig.h` and then I ran the code with some small modifications:

~~~
void seek_test()
{
    int rc[6];
    const int clusterSize = 4096;
    static const char FNAME[] = "/testFile.txt";

    char *buffer = pvPortMalloc(clusterSize);
    if( buffer != NULL )
    {
        memset(buffer, 'A', clusterSize);
        FF_FILE *file = ff_fopen(FNAME, "w");
        if( file != NULL )
        {
            rc[0] = ff_fseek(file, 0, FF_SEEK_SET);
            rc[1] = ff_fwrite(buffer, 1, clusterSize, file);
            rc[2] = ff_fclose(file);
            memset(buffer, 'B', clusterSize);
            file = ff_fopen(FNAME, "r+");
            if( file != NULL )
            {
                rc[3] = ff_fseek(file, clusterSize, FF_SEEK_SET);
                rc[4] = ff_fwrite(buffer, 1, clusterSize, file);
                rc[5] = ff_fclose(file);
                FF_PRINTF( "Results = %d %d %d %d %d %d\n",
                    rc[ 0 ], rc[ 1 ], rc[ 2 ], rc[ 3 ], rc[ 4 ], rc[ 5 ] );
            }
        }
        vPortFree( buffer );
    }
}
~~~
It shows `Results = 0 4096 0 0 4096 0`. 

You are calling `malloc()` without testing the result. Normally, FreeRTOS projects use `pvPortMalloc()`, and the result should always be tested.

**Comment by MateuszKlatecki** [comment]
@htibosch I'm using iMXRT1062 (Cortex-M7) with official drivers from NXP. 

As for malloc, I have MallocFailedHook configured and I would know the allocation failed.

The main question after executing this code is the content of the file correct for you? Did you format the card using the same cluster size as in the code? If so, everything would indicate that it is something with drivers or read / write block functions for me.

**Comment by htibosch** [comment]
> As for malloc, I have MallocFailedHook configured and I would know the allocation failed.

That hook will never be called if you use the clib function `malloc()`. But still, it is good practive to check the result of any `malloc()` or `pvPortMalloc()` function.

And make sure you define this function:
~~~
void vApplicationMallocFailedHook( void )
{
}
~~~
with C-linkage ( as opposed to C++ linkage ).

Yes I checked the contents of the file created and it was as expected: 4 KB of 'A's, and 4 KB of 'B's.

I think that the cluster size of my 8 GB card is bigger than 4 KB, but I did not check that.

**Comment by MateuszKlatecki** [comment]
Let's leave the malloc matter aside because it doesn't matter at the moment.

**It is very important that the cluster size is the same as the size of the saved data / position in the file.**

When I was doing the test with a 16kB cluster, but the amount of data was 4kB, everything worked fine. So please make sure the cluster size in the card is equal to the size in the program.

The 8GB card can be formatted with a 4kB cluster: https://support.microsoft.com/en-us/topic/default-cluster-size-for-ntfs-fat-and-exfat-9772e6f1-e31a-00d7-e18f-73169155af95

**Comment by htibosch** [comment]
> t is very important that the cluster size is the same as the size of the saved data / position in the file.

All right, I got an 8 GB micro SD-card, which I formatted with a cluster size of 4096 bytes and I can replicate the problem that you encounter!

I will prepare a pull request which will solve this problem. I will let you know in this issue.

Thanks for reporting!

**Comment by htibosch** [comment]
Mateusz, please find a patched version of ff_file.c [attached to this post](https://github.com/FreeRTOS/Lab-Project-FreeRTOS-FAT/files/6415782/ff_file.zip).

I added a few lines of code at the end of `FF_ExtendFile()`:
~~~c
if( pxFile->ulFilePointer == pxFile->ulFileSize )
{
    /* Writing at the end of a file, while new clusters have just been added.
     * Make sure that the fields 'ulCurrentCluster' and 'ulAddrCurrentCluster' are
     * set correctly.
     */
    FF_Error_t xTempError = FF_ERR_NONE;
    uint32_t ulNewCluster = FF_getClusterChainNumber( pxIOManager, pxFile->ulFilePointer, 1 );

    FF_LockFAT( pxIOManager );
    {
        pxFile->ulAddrCurrentCluster = FF_TraverseFAT( pxIOManager, pxFile->ulObjectCluster, ulNewCluster, &( xTempError ) );
        pxFile->ulCurrentCluster = ulNewCluster;
    }
    FF_UnlockFAT( pxIOManager );

    if( FF_isERR( xError ) == pdFALSE )
    {
        xError = xTempError;
    }
}
~~~
I tested it with cluster sizes of 1, 2, 4, 8, and 16 KB.

It would be great if you can check if it also works for you.

Thanks, Hein

**Comment by MateuszKlatecki** [comment]
I checked this patch and it fixes my problems. Thanks for the quick and effective help.

**Comment by htibosch** [comment]
I created a patch for this: #17 
If you want you can now close the issue.
Thanks, Hein
