### ISSUE TITLE
Missing FreeRTOSFATConfig.h file

### ISSUE THREAD

**Issue by alpereira7** [FreeRTOS/Lab-Project-FreeRTOS-FAT#36]
In `include/ff_headers.h` there are
```
#include "FreeRTOSFATConfig.h"
#include "FreeRTOSFATConfigDefaults.h"
```
However I can't find the `FreeRTOSFATConfig.h` file. Where can I find it?

**Comment by htibosch** [comment]
Hello @alpereira7, the file `FreeRTOSFATConfig.h` is like `FreeRTOSConfig.h` for the kernel and like `FreeRTOSIPConfig.h` for [FreeRTOS+TCP](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP). You are supposed to provide them.

If you want examples of `FreeRTOSFATConfig.h`, please have a look at one of the projects [here](https://github.com/htibosch/freertos_plus_projects). You can clone the repo and look `FreeRTOSFATConfig.h` files.

What platform are you working on?

**Comment by alpereira7** [comment]
> What platform are you working on?

I'm working on STM32H7xx.
I've found an exemple in an official package from FreeRTOS : `160919_FreeRTOS_Labs\FreeRTOS-Plus\Demo\FreeRTOS_Plus_TCP_and_FAT_STM32F4xxx\src\FreeRTOSFATConfig.h` but I'm not sure how it'll work with my STM32H7xx.

I will have a look at your project, thanks.

**Comment by htibosch** [comment]
> 160919_FreeRTOS_Labs

That is from 19 September 2016, a long time ago.

[Here](https://github.com/htibosch/freertos_plus_projects/tree/master/STM32H747_cube/CM7/Core/Inc) are the config files for STM32H747, but without +FAT.

[These](https://github.com/htibosch/freertos_plus_projects/tree/master/plus/stm32F7/Inc) are the configuration files for an STM32F7 project that uses +FAT as well.

Note that there have been many posts about the STM32H7 and TCP/IP.

**Comment by archigup** [comment]
Closing since question has been answered; feel free to open a new issue if you have further trouble or questions.
