### ISSUE TITLE
[Feature Request] Fix typo in FF_CreateIOManger

### ISSUE THREAD

**Issue by fnadeau** [FreeRTOS/Lab-Project-FreeRTOS-FAT#40]
**Is your feature request related to a problem? Please describe.**
There is a mismatch between FF_CreateIOManger() and FF_DeleteIOManager() on how "manager" is spelled.

**Describe the solution you'd like**
- Rename FF_CreateIOManger() to FF_CreateIOManager()
- Add a macro in FreeRTOSFATConfigDefaults.h or ff_old_config_defines.h to support old implementation that still use FF_CreateIOManger()
- Add deprecation note to documentation.

**Describe alternatives you've considered**
Same bue FF_DeleteIOManager() -> FF_DeleteIOManger()

**Additional context**
N/A

**Comment by htibosch** [comment]
@fnadeau, thank you for this catch! This misspelling has been there for many years, which shows how bad we actually read.

Of course it should have been:
~~~c
FF_IOManager_t * FF_CreateIOManager();
FF_ERROR FF_DeleteIOManager();
~~~
It's been like that for 8 years. Before that they were called differently.

Maybe this would be handy:
~~~
#define FF_CreateIOManger FF_CreateIOManager
#define FF_DeleteIOManger FF_DeleteIOManager
~~~

Thanks

**Comment by AniruddhaKanhere** [comment]
@fnadeau thank you for reaching out to us and pointing out that issue.

Would you be willing to contribute to the repository by creating a pull request (PR) with the changes the @htibosch suggested?

**Comment by fnadeau** [comment]
I have this: https://github.com/fnadeau/Lab-Project-FreeRTOS-FAT/tree/issues/40_typo

I'll do some test tomorrow and if all goes well I'll open a pull request.
