### ISSUE TITLE
[DOC] Error in ff_fopen() documentation

### ISSUE THREAD

**Issue by carlk3** [FreeRTOS/Lab-Project-FreeRTOS-FAT#52]
**Describe the issue**
Please describe the issue and expected clarification in concise language.

At [ff_fopen](https://www.freertos.org/FreeRTOS-Plus/FreeRTOS_Plus_FAT/stdio_API/ff_fopen.html), pcMode, Letter "w", Mode, it says "Open a file for reading and writing." This in incorrect. It is only opened for writing. If you try to read, permission is denied.

**Reference**
Please attach the URL at which you are experiencing the issue.

https://www.freertos.org/FreeRTOS-Plus/FreeRTOS_Plus_FAT/stdio_API/ff_fopen.html

**Screenshot**
If applicable, please attach screenshot.

**Browser**
- Browser: [e.g. Chrome]
- Version: [e.g. 80.0.3987.132]

**Comment by htibosch** [comment]
@carlk3 wrote:
> At [ff_fopen](https://www.freertos.org/FreeRTOS-Plus/FreeRTOS_Plus_FAT/stdio_API/ff_fopen.html), pcMode, Letter "w", Mode, it says "Open a file for reading and writing." This in incorrect. If you try to read, permission is denied.

Out of curiosity, I tried the same under Linux and Windows: both `fseek()` and `fread()` return zero when the files was created with the "w"-flag:

~~~c
    FILE *fp = fopen (fname, "w");
    if (fp != NULL) {
        fprintf(fp, "Hello world\n");
        int rc = fseek (fp, 0, SEEK_SET);
        if (rc == 0) {
            char contents[ 32 ];
            rc = fread (contents, 1, sizeof contents - 1, fp);
        }
        fclose (fp);
    }
~~~
I also tried to create the file with "w+", that does allow to write and read from the same hand.e

So let's change the documentation:
~~~diff
-    Open a file for reading and writing. If the file ...
+    Open a file for writing. If the file ...
~~~
Thank for your suggestion!

**Comment by carlk3** [comment]
> I also tried to create the file with "w+", that does allow to write and read from the same hand.e

Of course, "w+" is not explicitly documented, although "r+" is.  Looking at the code for `uint8_t FF_GetModeBits( const char * pcMode )`, apparently you can mix and match individual characters in the string and order is not important. So, "+" could be documented separately. 

I have found that the pcMode string "rw" works well in this case.

**Comment by kar-rahul-aws** [comment]
Hi @carlk3, thanks for catching this for us. The documentation should be updated shortly. Will close the issue once the pages are updated. We will be updating the content as @htibosch suggested for now.

**Comment by kar-rahul-aws** [comment]
We have updated the content in the [page](https://freertos-wordpress.corp.amazon.com/FreeRTOS-Plus/FreeRTOS_Plus_FAT/stdio_API/ff_fopen.html)

**Comment by AniruddhaKanhere** [comment]
I cannot see the change on the official page: https://freertos.org/FreeRTOS-Plus/FreeRTOS_Plus_FAT/stdio_API/ff_fopen.html.

Once that is fixed, the issue can be closed.

**Comment by moninom1** [comment]
Thank you @AniruddhaKanhere for pointing it out, working on updating it the official page, will update once done.

**Comment by moninom1** [comment]
The change is updated on the official page, Hence closing the issue. Thank you
