### ISSUE TITLE
[DOC] Error in ff_stat documentation

### ISSUE THREAD

**Issue by carlk3** [FreeRTOS/Lab-Project-FreeRTOS-FAT#57]
**Describe the issue**
Please describe the issue and expected clarification in concise language.

[ff_stat](https://www.freertos.org/FreeRTOS-Plus/FreeRTOS_Plus_FAT/stdio_API/ff_stat.html) says
```
int ff_stat( const char *pcFileName, ff_stat_struct *pxStatBuffer );
```
and the example has
```
ff_stat_struct xStat;
```
However, if you try it, you'll get "identifier "ff_stat_struct" is undefined".

I think you mean `FF_Stat_t`.

**Reference**
Please attach the URL at which you are experiencing the issue.

https://www.freertos.org/FreeRTOS-Plus/FreeRTOS_Plus_FAT/stdio_API/ff_stat.html

**Screenshot**
If applicable, please attach screenshot.

**Browser**
- Browser: [e.g. Chrome]
- Version: [e.g. 80.0.3987.132]

**Comment by htibosch** [comment]
Hello @carlk3, thank you for brining this to our attention. In today's repo the function is indeed declared as:
~~~
int ff_stat( const char * pcFileName,
                 FF_Stat_t * pxStatBuffer );
~~~
I will ask to have it changed.

**Comment by ydhuang28** [comment]
Hi @carlk3, thanks for catching this for us. I'm working on a fix and the documentation should be updated shortly. Will close the issue once the pages are updated.

**Comment by kar-rahul-aws** [comment]
Hi @carlk3 
The documentation has been updated. You can have a look [here](https://www.freertos.org/FreeRTOS-Plus/FreeRTOS_Plus_FAT/stdio_API/ff_stat.html)

**Comment by carlk3** [comment]
Looks good. Thanks!
