### ISSUE TITLE
When will +FAT release a stable version?

### ISSUE THREAD

**Issue by cheney-du** [FreeRTOS/Lab-Project-FreeRTOS-FAT#6]
I have a few question:
+ When will +FAT release a stable version?
+ Will ROM Disk be supported in the future?
+ Will NAND FLASH FTL be supported？
Thanks.

**Comment by htibosch** [comment]
Hello,

> When will +FAT release a stable version?

FreeRTOS+FAT is not used as often as [FreeRTOS+TCP](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP) is. For that reason, it doesn't receive as much attention, making it MISRA compliant, create unit-tests, running CBMC etc.

It has been tested though in integration tests, in real live. It has been out for many years, and we rarely see complaints.

> Will ROM Disk be supported in the future?

What does ROM Disk support need, beside a read-only driver? If you have a function that can read a sector from that disk, you almost have a working driver.

> Will NAND FLASH FTL be supported？

Same answer: you will need both a read() and a write() function and there you go.

If you need any specific help for creating a new driver, you can post your questions right here in this post.

**Comment by RichardBarry** [comment]
Just for future reference we prefer questions to be posted to the support forum here: https://forums.freertos.org - you can use your Github account to log in to post.
