### ISSUE TITLE
warning: redundant redeclaration of 'snprintf'

### ISSUE THREAD

**Issue by Azq2** [FreeRTOS/Lab-Project-FreeRTOS-FAT#9]
This really necessary in 2k21?

Seems like dirty workaround for specific broken environment.

https://github.com/FreeRTOS/Lab-Project-FreeRTOS-FAT/blob/master/ff_error.c#L37

**Comment by htibosch** [comment]
> This really necessary in 2k21?

The +FAT library already exists for more than a decade. I have forgotten which environment needed it.
It's perfectly OK if you want to create a PR that takes the declaration away.

Thanks, Hein
